const routes = [
  { endpoint: "/login", method: "POST", action: "db.login" },
  { endpoint: "/logout", method: "GET", action: "db.logout" },
  // { endpoint: "/auth/google", method: "GET", action: "db.login" },
  // { endpoint: "/metamask/login", method: "POST", action: "db.login" }, 
  { endpoint: "/signup", method: "POST", action: "db.signup" }, 
  { endpoint: "/userinfo_copy", method: "POST", action: "db.userinfo_copy" }, 
  { endpoint: "/check-auth", method: "GET", action: "NA" }, 
  //
  { endpoint: "/userinfo_view/:label", method: "GET", action: "db.userinfo_view" }, 
  { endpoint: "/userinfo_view_settings", method: "GET", action: "db.userinfo_view" },
  { endpoint: "/userinfo_upload", method: "POST", action: "db.userinfo_upload" },
  { endpoint: "/userinfo_update", method: "POST", action: "db.userinfo_update" },
  { endpoint: "/userinfo_update_single", method: "POST", action: "db.userinfo_update_single" },
  { endpoint: "/userinfo_remove", method: "POST", action: "db.userinfo_remove" },  
  //
  { endpoint: "/post_create", method: "POST", action: "gpt.post_create" },  
  { endpoint: "/post_update", method: "POST", action: "db.post_update" }, 
  { endpoint: "/post_view/:id", method: "GET", action: "db.post_view" },
  { endpoint: "/search_company", method: "POST", action: "db.search_company" }, 
  { endpoint: "/refine_yaml", method: "POST", action: "gpt.refine_yaml" }, 
  { endpoint: "/text_to_latex", method: "POST", action: "gpt.text_to_latex" }, 
  { endpoint: '/extension_fill_form', method: 'POST', action: 'gpt.extension_fill_form' },   
  { endpoint: "/extension_post_create", method: "POST", action: "gpt.extension_post_create" },
  { endpoint: "/extension_post_update", method: "POST", action: "db.extension_post_update" },
  { endpoint: "/extension_ask_question", method: "POST", action: "gpt.extension_ask_question" }, 
  { endpoint: "/edit", method: "POST", action: "gpt.edit" }
  // { endpoint: "/view-db-structure", method: "GET", action: "viewDbStructure" }, 
  // { endpoint: "/generate_pdf", method: "POST", action: "db.generate_pdf" }, 
  // { endpoint: "/email-generate", method: "POST", action: "gpt.email_generate" },
  // { endpoint: "/email-send", method: "POST", action: "gpt.email_send" },
  // { endpoint: "/apply", method: "POST", action: "gpt.email_send" }, 
  // { endpoint: "/extension-post-fetch", method: "POST", action: "db.extension_post_fetch" },
  // { endpoint: "/post-update-status", method: "POST", action: "db.post_update_status" },
  // { endpoint: "/post-remove", method: "POST", action: "gpt.remove_post" },
  // { endpoint: "/post_view/:id", method: "GET", action: "db.post_view" },
  // { endpoint: "/posts-bulk-create", method: "GET", action: "gpt.posts_bulk_create" },
  // { endpoint: "/company-update", method: "POST", action: "db.company_update" },
  // { endpoint: "/companys-view", method: "GET", action: "gpt.companys_view" },
  // { endpoint: "/company-view/:id", method: "GET", action: "gpt.company_view" },
  // { endpoint: "/sitemap", method: "POST", action: "gpt.sitemap" },
  // { endpoint: "/sitemap-fetch", method: "POST", action: "gpt.sitemap" },
  // { endpoint: "/sitemap-crawl", method: "POST", action: "gpt.sitemap" },
  // { endpoint: "/sitemap-crawl-board-links", method: "POST", action: "gpt.sitemap_crawl_board_links" },
  // { endpoint: "/sitemap-create-link", method: "POST", action: "db.sitemap_create_link" },
  // { endpoint: "/sitemap-remove-link", method: "POST", action: "gpt.sitemap_remove_link" },
  // { endpoint: "/sitemap-update-link", method: "POST", action: "gpt.sitemap_update_link" },
  // { endpoint: "/extracts-create-for-post", method: "POST", action: "gpt.extracts_create_for_post" },
  // { endpoint: "/extract-create-for-post", method: "POST", action: "gpt.extract_create_for_post" },
  // { endpoint: "/extracts-view-for-post/:id", method: "GET", action: "db.extracts_view_for_post" },
  // { endpoint: "/extract-update", method: "POST", action: "db.extract_update" },
  // { endpoint: "/apply", method: "POST", action: "rzecord_company.email_send" },

];

export { routes };
